# Generated by Django 6.0.6 on 2026-07-02 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_actual', models.PositiveSmallIntegerField(choices=[(1, 'Paso 1: Factores relevantes'), (2, 'Paso 2: Subfactores'), (3, 'Paso 3: Resultado')], default=1)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completada', 'Completada')], default='en_progreso', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia_sugerida_snapshot', models.PositiveSmallIntegerField(choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')])),
                ('importancia_decisor', models.PositiveSmallIntegerField(choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')], default=1)),
                ('importancia_relativa', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')], null=True)),
                ('alcance', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('relevante', models.BooleanField(default=False)),
                ('ponderacion_media', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('clasificacion_foda', models.CharField(blank=True, max_length=20)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='evaluations.evaluacion')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_factor', to='catalog.factor')),
            ],
            options={
                'verbose_name': 'Factor evaluado',
                'verbose_name_plural': 'Factores evaluados',
                'unique_together': {('evaluacion', 'factor')},
            },
        ),
        migrations.CreateModel(
            name='SoftwareEvaluado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares_evaluados', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Software evaluado',
                'verbose_name_plural': 'Softwares evaluados',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluations.softwareevaluado'),
        ),
        migrations.CreateModel(
            name='EvaluacionSubfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cumplimiento', models.PositiveSmallIntegerField(choices=[(1, 'No cumple el requisito'), (2, 'Desconozco si cumple requisito'), (3, 'Cumple parcialmente el requisito'), (4, 'Cumple el requisito')], default=1)),
                ('evaluacion_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactores', to='evaluations.evaluacionfactor')),
                ('subfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_subfactor', to='catalog.subfactor')),
            ],
            options={
                'verbose_name': 'Subfactor evaluado',
                'verbose_name_plural': 'Subfactores evaluados',
                'unique_together': {('evaluacion_factor', 'subfactor')},
            },
        ),
    ]
