# Generated by Django 5.2.15 on 2026-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_evaluacion_id_alter_evaluacionfactor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionfactor',
            name='incluido',
            field=models.BooleanField(default=True, verbose_name='Incluido en esta evaluación'),
        ),
    ]
