# Generated by Django 5.2.15 on 2026-07-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_empresa_id_alter_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cuestionario_completado',
        ),
    ]
