# Generated by Django 6.0.6 on 2026-07-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('alcance', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo'), ('ambos', 'Ambos')], default='interno', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='catalog.dimension')),
            ],
            options={
                'verbose_name': 'Factor',
                'verbose_name_plural': 'Factores',
                'ordering': ['dimension', 'nombre'],
                'unique_together': {('nombre', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='Subfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactores', to='catalog.factor')),
            ],
            options={
                'verbose_name': 'Subfactor',
                'verbose_name_plural': 'Subfactores',
                'ordering': ['factor', 'id'],
            },
        ),
    ]
