# Generated by Django 5.2.15 on 2026-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_dimension_id_alter_factor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='importancia_base',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')], default=2, help_text="Valor de partida del catálogo (equivalente a 'Sugerida' en factors.csv). Se usa como respuesta por defecto del cuestionario de importancia para empresas/factores nuevos, antes de que el decisor la ajuste.", verbose_name='Importancia sugerida'),
        ),
    ]
