# Generated by Django 5.2.15 on 2026-07-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cargar_catalogo_guiosad'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='termino_busqueda_en',
            field=models.CharField(blank=True, help_text='Término en inglés usado para consultar evidencia bibliográfica en Scopus (la literatura indexada es mayormente en inglés). Si se deja vacío, se usa el nombre del factor tal cual.', max_length=150, verbose_name='Término de búsqueda (Scopus, en inglés)'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='importancia_base',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')], default=2, help_text="Valor experto de partida del catálogo (equivalente a 'Sugerida' en factors.csv). Se combina con la evidencia bibliográfica de Scopus (ver catalog.services.calcular_importancia_sugerida) para calcular la Importancia Sugerida (IS) de cada nueva evaluación; si Scopus no está disponible, este valor se usa tal cual.", verbose_name='Importancia sugerida'),
        ),
    ]
