# Generated by Django 6.0.6 on 2026-07-02 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialImportancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_nuevo', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_importancia', to='accounts.empresa')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.factor')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de importancia',
                'verbose_name_plural': 'Historial de importancia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilImportanciaFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia', models.PositiveSmallIntegerField(choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')], default=2)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_importancia', to='accounts.empresa')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_importancia', to='catalog.factor')),
            ],
            options={
                'verbose_name': 'Perfil de importancia por factor',
                'verbose_name_plural': 'Perfiles de importancia por factor',
                'unique_together': {('empresa', 'factor')},
            },
        ),
    ]
