# Generated by Django 6.0.6 on 2026-07-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('A', 'No es posible adoptar'), ('B', 'Es posible adoptar con reservas'), ('C', 'Adoptar')], max_length=1)),
                ('texto', models.TextField()),
                ('total_fortalezas', models.PositiveSmallIntegerField(default=0)),
                ('total_oportunidades', models.PositiveSmallIntegerField(default=0)),
                ('total_debilidades', models.PositiveSmallIntegerField(default=0)),
                ('total_amenazas', models.PositiveSmallIntegerField(default=0)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacion', to='evaluations.evaluacion')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
    ]
