# Generated by Django 5.2.15 on 2026-07-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recomendacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='puntaje_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
