# Generated by Django 5.2.15 on 2026-07-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recomendacion_puntaje_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='nivel',
            field=models.CharField(choices=[('A', 'Adoptar'), ('B', 'Es posible adoptar con reservas'), ('C', 'No es posible adoptar')], max_length=1),
        ),
    ]
